### ISSUE TITLE
Error iframe

### ISSUE THREAD

**Issue by gabrielopereira** [geerlingguy/youtube_chat_crawler#2]
Hi,

Thanks for your work with this! I seem to be getting the following error. Has there been a change on Youtube, or could this be caused by my side?

"Couldn't find live_chat_replay iframe. Maybe try running again?"

**Comment by geerlingguy** [comment]
That happens maybe 50% of the time I try running the crawler... I think YouTube's API/CDN might deny requests a lot, and this script doesn't have any mechanism for retries like YouTube's web UI javascript does, so the best option is to wait a few seconds then try again.

Sometimes I've had to do that (wait, then try, then wait, then try) four or five times before it runs through and works.

**Comment by vetrivendhan** [comment]
I tried several times, But unable to fetch the data

_**ter$ ./YoutubeChatReplayCrawler.py http://www.youtube.com/watch?v=oTu2-cKwTl0**_
Couldn't find live_chat_replay iframe. Maybe try running again?
